sudo: false
language: python
python:
  - "2.7"
env:
  - PYTHONPATH="$TRAVIS_BUILD_DIR/app/"
install:
  - cp app/app/local.env.dist app/app/.env
  - pip install -r requirements-test.txt
script:
  - pytest
after_success:
  - pip install codecov
  - codecov
