sudo: false
language: python
python:
  - "3.6"
env:
  - PYTHONPATH="$TRAVIS_BUILD_DIR/app/"
install:
  - cp app/app/local_settings.py.dist app/app/local_settings.py
  - pip install -r requirements/test.txt
script:
  - pytest -p no:ethereum
after_success:
  - pip install codecov
  - codecov
addons:
  postgresql: "9.6"
