sudo: false
language: python
python:
  - "3.6"
node_js:
  - "8"
env:
  - PYTHONPATH="$TRAVIS_BUILD_DIR/app/"
cache:
  directories:
    - $HOME/.cache/pip
    - node_modules
install:
  - npm install
  - cp app/app/travis.env app/app/.env
  - pip install -r requirements/test.txt
script:
  - npm run eslint
  - pytest -p no:ethereum
after_success:
  - pip install codecov
  - codecov
addons:
  postgresql: "9.6"
